### PR TITLE
Add in support for RTE tables

### PR DESCRIPTION
**Pull request by JayyajGH**
Add in support for RTE tables that have recently been implemented by Contentful

### CODE REVIEW

**Comment by JayyajGH** [comment]
Here are the release notes from Contentful

https://www.contentful.com/developers/changelog/#create-tables-in-the-rich-text-editor

**Comment by tolgap** [comment]
@JayyajGH thank you for including tests as well with your PR. Amazing work!

**Comment by tolgap** [comment]
Published in `v2.1.0` 🎉

**Comment by JayyajGH** [comment]
Awesome!  Thanks for merging @tolgap!

**Pull request merged**
